### ISSUE TITLE
Cannot see lakedb

### ISSUE THREAD

**Issue by Matlock1000D** [MicrosoftLearning/mslearn-synapse#6]
# Module: 00
#### Step: 5.

I have followed the instructions until this point. The instructions say that I should see "A serverless SQL pool database named lakedb." However, only the dedicated SQL pool database is shown. I have not encountered any errors up until this poin.

Repro steps:

1. Follow instructions in the tutorial.

**Comment by TheJamesHerring** [comment]
I will look into this.
