### ISSUE TITLE
mod-01 | Task: View the ingested data, instruction a little bit unclear

### ISSUE THREAD

**Issue by Josh-BI-UK** [MicrosoftLearning/mslearn-synapse#7]
# Module: 01-Explore-Azure-Synapse
#### Link To section/paragraph: https://github.com/MicrosoftLearning/mslearn-synapse/blob/master/Instructions/Labs/01-Explore-Azure-Synapse.md#view-the-ingested-data

**Description of issue:**
There is an assumed "user knows what to do next", jump in the step-by-step instructions.

_The screenshot explains the need to: _

1. Select and expand the 'Azure Data Lake Storage Gen2' option.
2. Select and expand the storage account created for your deployment (i.e synapsexxxxxxx)
3. Select the 'files (Primary)' container
4. In the item explorer window, your container should open in a new tab and display the 'Products.csv' file.

_However, the instructions jump straight to:_

**Linked** tab and expand the **Product Files** hierarchy….
You don’t see anything associated with ‘**Product Files**’ until you have completed the drill-down process which isn’t clearly explained how to perform those steps. The screenshot is great, I found the instruction a little bit unclear. Thank you in advance for considering my change suggestion, @Josh_BI_UK

**Comment by TheJamesHerring** [comment]
I will look into a more standard way to explain how to navigate a hierarchy from its root to the end in the next review cycle. Thank you for your perspective.
JH
